Allow for custom base URIs for GDPR support
prschmid/zoomus pull request #188
Opened 2021-03-24 12:33 UTC by prschmid

Closes #10

2021-03-24 13:28 UTC, prschmid commented on tox.ini
> +    -rrequirements-tests.txt
@mfldavidson I know you removed the extra `r` in https://github.com/prschmid/zoomus/commit/d16dc043d1d27aa638db262e75ead7f407af93a8, but looks like this isn't a typo and travis fails.  See this failing build (and then the subsequent fix). https://travis-ci.org/github/prschmid/zoomus/jobs/764225842

2021-03-29 18:05 UTC, gregorydlogan requested changes
Minor nits noticed in testing.

Might also be worth adding a note that the EU endpoint will not function unless your account is an EU account.  Neither my credentials, nor my clients work on the EU endpoints yet, but my client is due to migrate tomorrow.  Will try to remember to check again.

2021-03-29 18:12 UTC, prschmid commented
@gregorydlogan Thanks for testing it out! I just pushed a commit with the added `/v2` to the `base_url`, and updated the documentation based on your suggestion.

Can you let me know how things pan out with your testing tomorrow with the EU enabled account? Once you give me the 👍 , I'll get this merged in. 

Thanks!

2021-04-01 18:43 UTC, prschmid commented
@gregorydlogan Glad to hear that all went well! Congrats! Thanks for your help in testing and will merge this in now.

2021-04-01 18:43 UTC, merged